### ISSUE TITLE
acronym_generate_scene.py

### ISSUE THREAD

**Issue by huaji98** [NVlabs/acronym#10]
Why is the cup under the table？
![2021-10-12 16-02-05 的屏幕截图](https://user-images.githubusercontent.com/34676402/136916917-0590604c-34a6-4763-96b3-b3be634b7e71.png)

**Comment by clemense** [comment]
Why shouldn't it be there?

**Comment by huaji98** [comment]
Shouldn't the cup be at the top of the table？

**Comment by clemense** [comment]
Shouldn't it be at the bottom of the table?
