### ISSUE TITLE
Not able to access shapenet.org

### ISSUE THREAD

**Issue by jucamohedano** [NVlabs/acronym#12]
Hi, 

I am trying to access https://www.shapenet.org/ but seems like the server is down because there is no response. Is there a way around this so that I can get access to the ShapeNetSem dataset?

Thank you.

**Comment by jucamohedano** [comment]
I have access now. Thank you.

**Comment by HowCCB** [comment]
> I have access now. Thank you.

oh, how did you do that, I meet the same problems these days.
