### ISSUE TITLE
data and website no longer accessible

### ISSUE THREAD

**Issue by kedarrajpathak** [NVlabs/acronym#20]
The link to download acronym.tar.gz and the website https://sites.google.com/nvidia.com/graspdataset are no longer accessible. Is this temporary or is the dataset not public anymore?

**Comment by clemense** [comment]
Thanks for pointing this out!  The website and dataset are now here: https://sites.google.com/view/graspdataset/

Let me know if there are still any accessibility problems.

**Comment by kedarrajpathak** [comment]
Thanks. The updated website and data download links are working.
