### ISSUE TITLE
script to convert ShapeNet meshes to simulation-compatible ones

### ISSUE THREAD

**Issue by seann999** [NVlabs/acronym#6]
This is more of a feature request. It seems like some people are struggling to convert the original meshes even with the instructions in the README, including myself (besides some errors for some meshes, my conversion script gets stuck for some reason).
Would be nice if there can be a bash script to reproduce the conversion process you guys did.

This is the script I'm using:
```
for fn in ~/data/shapenetsem/models-OBJ/models/*.obj
do
  rm temp.watertight.obj

  timeout -sKILL 10 ./manifold "$fn" temp.watertight.obj -s
  
  if [ $? != 0 ]; then
    echo "skipping object"
  else
    out="$(basename $fn)"
    ./simplify -i temp.watertight.obj -o ~/data/shapenetsem/models-OBJ/simplified/$out -m -r 0.02
  fi
done
```

**Comment by seann999** [comment]
Only processing the 7897 models mentioned in the acronym dataset (the IDs in the filenames) instead of all 24980 in the original ShapeNetSem seems to have worked.

**Comment by ymxlzgy** [comment]
> Only processing the 7897 models mentioned in the acronym dataset (the IDs in the filenames) instead of all 24980 in the original ShapeNetSem seems to have worked.

Do you solve the stuck problem?

**Comment by clemense** [comment]
What exactly is the problem that you are referring to?

**Comment by ymxlzgy** [comment]
> What exactly is the problem that you are referring to?

I use this script but only obtaining about 1000 meshes because this script can get stuck in the middle of the mesh generation. How can I solve it?

**Comment by clemense** [comment]
You could increase the timeout duration. It's currently set to 10 seconds.

**Comment by ymxlzgy** [comment]
> You could increase the timeout duration. It's currently set to 10 seconds.

I have extended it even to 1000... But I only got 6880 objects although it indeed increases. Could you upload the generated obj file to google drive to solve this problem once for all?

**Comment by playertr** [comment]
Here's my script:
```
"""
convert_meshes.py
Process the .obj files and make them waterproof and simplified.
"""
import os
import subprocess
from tqdm import tqdm
from multiprocessing import Pool, cpu_count

GRASPDIR = "/path/to/acronym/data/grasps/"
OBJDIR = "/path/to/acronym/data/shapenetsem/models-OBJ/"
MANIFOLD_PATH = "/path/to/Manifold/build/manifold"
SIMPLIFY_PATH = "/path/to/Manifold/build/simplify"

## Grab the object file names from the grasp directory
hashes = []
for fname in os.listdir(GRASPDIR):
    tokens = fname.split("_")
    assert(len(tokens) == 3)
    hashes.append(tokens[1])

## Define function to process a single file
def process_hash(h):
    """Process a single object file by calling a subshell with the mesh processing script.

    Args:
        h (string): the hash denoting the file type
    """
    obj = OBJDIR + 'models/' + h + ".obj"

    if not os.path.isfile(obj):
        return
    
    # Waterproof the object
    temp_name = f"temp.{h}.watertight.obj"
    completed = subprocess.run(["timeout", "-sKILL", "30", MANIFOLD_PATH, obj, temp_name], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    if completed.returncode != 0:
        print(f"Skipping object (manifold failed): {h}")
        return
            
    # Simplify the object
    outfile = OBJDIR + "simplified/" + h + ".obj"
    completed = subprocess.run([SIMPLIFY_PATH, "-i", temp_name, "-o", outfile, "-m", "-r", "0.02"],  stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

    if completed.returncode != 0:
        print(f"Skipping object (simplify failed): {h}")
        
## Issue the commands in a multiprocessing pool
with Pool(cpu_count()-2) as p:
    examples = list(
        tqdm(
            p.imap_unordered(process_hash, hashes),
            total=len(hashes)
        )
    )
```
