### ISSUE TITLE
I would like to ask about the "grasps/h5" h5 format file, what tools can be quickly generated?

### ISSUE THREAD

**Issue by ggzzzzz628** [NVlabs/acronym#8]
I would like to ask about the "grasps/h5" h5 format file, what tools can be quickly generated?

NVlabs/contact_graspnet: Efficient 6-DoF Grasp Generation in Cluttered Scenes
https://github.com/NVlabs/contact_graspnet

I am studying this project, the data set format needs h5 file for training, so I do not know how to generate h5 file at present

**Comment by clemense** [comment]
For an overview of libraries that can be used to interface the hierarchical data format in various languages, see: https://en.wikipedia.org/wiki/Hierarchical_Data_Format#Interfaces.

For Python I recommend https://www.h5py.org/.

**Comment by ggzzzzz628** [comment]
> For an overview of libraries that can be used to interface the hierarchical data format in various languages, see: https://en.wikipedia.org/wiki/Hierarchical_Data_Format#Interfaces.
> 
> For Python I recommend https://www.h5py.org/.

I know...
but the question I would like to ask is, is there a quick way to generate the h5 file in the ACRONYM project, because I don't know what the specific data format in the H5 is...
Is there documentation for h5 files? (shape, data meaning, etc.)

**Comment by clemense** [comment]
You can find the structure of the h5 files here: https://sites.google.com/nvidia.com/graspdataset.
